### PR TITLE
Fix gulpfile, add fullscreen.js

### PR DESCRIPTION
**Pull request by nofxx**

### CODE REVIEW

**Comment by frm** [comment]
Can you add the `fullscreen.js` file? I missed that while updating to match the original repo.

**Comment by nofxx** [comment]
Haha now I see that too. Adding it!
Ty for the gulpfile!

**Comment by nofxx** [comment]
A propósito, caro amigo lusófono, podemos falar no bom e velho portuga!
Colônia aqui =D

**Comment by nofxx** [comment]
There's something else missing... trying to figure out. Fullscreen won't open in this fork.

**Comment by nofxx** [comment]
Looks like it's all good now!

**Comment by frm** [comment]
Obrigado!

I was still testing the updates in this fork, seems to be nice, now! :+1: 

Please note that this fork has a couple of small differences, if you intend to use it:
- It allows setting the editor value as a blank value
- It allows passing a default value to the editor

I'll update the README to include that.

**Comment by nofxx** [comment]
Sounds good additions, you should pull request!
Not to mention the gulpfile: All kudos to @WesCossick (going to thank him later) MDE is the best markdown editor now, great work. But why not provide us with the build tools?

update: gulpfile wasn't the best: the `mv source\ folder src`

**Comment by frm** [comment]
Yea, big shout out to @WesCossick, great job.

I renamed the `source files` directory mainly because in a Unix environment it's kind of annoying to work with a directory with spaces in its name.

I also didn't check the way the files depend on each other, so I just hardcoded the gulpfile with the `.js` files to compile in the order specified in the original repository.

**Comment by nofxx** [comment]
Adding the last feature I think it's missing: side by side preview.

Already got it to work, looks perfect! Last issue: sync scrolls!

Totally lost.

**Comment by nofxx** [comment]
Actually it was very easy. Codemirror is great.
Just my lack of JS skills that took some time.
If you want to give it a try:  https://github.com/nofxx/simplemde-markdown-editor/commits/sidebyside

**Comment by WesCossick** [comment]
I don't use gulp.js on a regular basis, so I'm not all that familiar with it. Though I'd like to implement it for SimpleMDE. Is your [gulpfile](https://github.com/frmendes/simplemde-markdown-editor/blob/master/gulpfile.js) working and accurate, assuming I rename `/source files/` to `/src/` and move the distribution files to `/dist/`?

**Comment by frm** [comment]
Yes. With the rename, by running `gulp` it will generate the minified files to `dist/`.

It compiles the JavaScript files in the order you specified [here](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/source%20files/README.md). The CSS files are compiled in no particular order. If you want, I can make a PR.

As I said above, I also added a couple of changes to your repo, besides the gulpfile. Namely, giving a default value to the editor and allowing to manually clear the editor value, by passing `value('')`. Both of these features are important for an Angular wrapper I'm working on. I don't know if you want to include them in the main repo, but I can make a PR for those as well.

**Comment by WesCossick** [comment]
Yeah, all of those changes will be great! Just create a PR for the gulpfile and for the value improvements.

Please compare against the `development` branch when you make the PR since I've just renamed the folders to `/src/` and `/dist/` in that branch.

**Pull request merged**
